import type { Metadata } from "next";
import { jbMono, majorMonoDisplay } from "./fonts";
import "./globals.css";

import { Provider } from "@/components/ui/provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${jbMono.variable} ${majorMonoDisplay.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className={`${jbMono.className} min-h-full flex flex-col`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
